### ISSUE TITLE
Use OpencvSharp Mat in SharpCV Or vice versa

### ISSUE THREAD

**Issue by Mghobadid** [SciSharp/SharpCV#5]
i think the only  problem in SharpCv is it  implements only a very small subset of opencv functionaility,
but the OpencvSharp  is more complete .

how can i those together?

**Comment by Oceania2018** [comment]
I need to re-wrap all interfaces, which is not much different from the workload of rewriting one. My goal is just to meet my needs. I don't need a complete OpenCV.

**Comment by henon** [comment]
@Mghobadid is there anything in SharpCv that is missing in OpencvSharp ?

**Comment by carloswbarros** [comment]
> @Mghobadid is there anything in SharpCv that is missing in OpencvSharp ?

GetRotationMatrix2D and WarpAffine for example.

**Comment by Oceania2018** [comment]
@carloswbarros https://github.com/SciSharp/SharpCV/blob/master/src/SharpCV/APIs/cv2.imgproc.cs#L124
